import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

// Browsable dictionary of the 100 UAE-SL reference signs. Loads the manifest
// generated by scripts/copy-reference-videos.mjs and lets the user search,
// filter by category, and open each ZHO reference clip in a video player.
export default function SignReference({ onClose }) {
  const [entries, setEntries] = useState([])
  const [loadError, setLoadError] = useState(null)
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('')
  const [selectedIdx, setSelectedIdx] = useState(null)

  useEffect(() => {
    fetch('/reference_index.json')
      .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json() })
      .then(setEntries)
      .catch(e => setLoadError(e.message))
  }, [])

  const categories = useMemo(
    () => Array.from(new Set(entries.map(e => e.category))).sort(),
    [entries],
  )

  // No "All" tab — fall back to the first category until the user picks one.
  const activeCategory = category && categories.includes(category) ? category : categories[0]

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    return entries.filter(e =>
      e.category === activeCategory &&
      (!q || e.label.toLowerCase().includes(q)),
    )
  }, [entries, activeCategory, query])

  // Changing the filter would shift indices, so close the player to avoid a
  // stale index pointing at the wrong clip.
  const changeQuery = e => { setSelectedIdx(null); setQuery(e.target.value) }
  const changeCategory = c => { setSelectedIdx(null); setCategory(c) }

  // Escape closes the player first, then the whole modal.
  useEffect(() => {
    const onKey = e => {
      if (e.key !== 'Escape') return
      setSelectedIdx(idx => { if (idx !== null) return null; onClose(); return null })
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  return (
    <div className="ref-overlay" onClick={onClose}>
      <div className="ref-modal" onClick={e => e.stopPropagation()}>
        <div className="ref-header">
          <span className="panel-label">Sign reference</span>
          <span className="ref-count">{filtered.length} signs</span>
          <button className="ref-close" onClick={onClose} aria-label="Close">✕</button>
        </div>

        <div className="ref-controls">
          <input
            type="text"
            className="ref-search"
            placeholder="Search a sign…"
            value={query}
            onChange={changeQuery}
            autoFocus
          />
          <div className="ref-cats">
            {categories.map(c => (
              <button
                key={c}
                className={`ref-cat${c === activeCategory ? ' active' : ''}`}
                onClick={() => changeCategory(c)}
              >
                {c}
              </button>
            ))}
          </div>
        </div>

        <div className="ref-grid">
          {loadError && (
            <div className="ref-empty">
              Couldn’t load reference videos ({loadError}). Run <code>npm run reference-videos</code>.
            </div>
          )}
          {!loadError && filtered.length === 0 && (
            <div className="ref-empty">No signs match “{query}”.</div>
          )}
          {filtered.map((e, i) => (
            <ReferenceCard key={e.word} entry={e} onClick={() => setSelectedIdx(i)} />
          ))}
        </div>
      </div>

      {selectedIdx !== null && filtered[selectedIdx] && (
        <SignPlayer
          list={filtered}
          index={selectedIdx}
          onIndexChange={setSelectedIdx}
          onClose={() => setSelectedIdx(null)}
        />
      )}
    </div>
  )
}

// Grid thumbnail: previews the clip on hover, opens the full player on click.
function ReferenceCard({ entry, onClick }) {
  const videoRef = useRef(null)

  const play = () => { videoRef.current?.play().catch(() => {}) }
  const pause = () => {
    const v = videoRef.current
    if (v) { v.pause(); v.currentTime = 0 }
  }

  return (
    <figure className="ref-card" onMouseEnter={play} onMouseLeave={pause} onClick={onClick}>
      <video
        ref={videoRef}
        className="ref-video"
        src={entry.video}
        muted
        loop
        playsInline
        preload="metadata"
      />
      <figcaption className="ref-caption">
        <span className="ref-label">{entry.label}</span>
        <span className="ref-cat-tag">{entry.category}</span>
      </figcaption>
    </figure>
  )
}

// Full-size player with native controls and prev/next navigation through the
// current (filtered) list.
function SignPlayer({ list, index, onIndexChange, onClose }) {
  const entry = list[index]
  const go = useCallback(
    delta => onIndexChange((index + delta + list.length) % list.length),
    [index, list.length, onIndexChange],
  )

  // Arrow keys navigate between clips.
  useEffect(() => {
    const onKey = e => {
      if (e.key === 'ArrowRight') go(1)
      else if (e.key === 'ArrowLeft') go(-1)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [go])

  return (
    <div className="player-overlay" onClick={onClose}>
      <div className="player-box" onClick={e => e.stopPropagation()}>
        <div className="player-header">
          <span className="player-title">{entry.label}</span>
          <span className="ref-cat-tag">{entry.category}</span>
          <button className="ref-close" onClick={onClose} aria-label="Close player">✕</button>
        </div>

        <div className="player-stage">
          {list.length > 1 && (
            <button className="player-nav prev" onClick={() => go(-1)} aria-label="Previous sign">‹</button>
          )}
          <video
            key={entry.video}   /* remount so the new clip autoplays from the start */
            className="player-video"
            src={entry.video}
            controls
            autoPlay
            loop
            playsInline
          />
          {list.length > 1 && (
            <button className="player-nav next" onClick={() => go(1)} aria-label="Next sign">›</button>
          )}
        </div>
      </div>
    </div>
  )
}
